FROM        node:9.1.0-alpine
MAINTAINER  Matt Finucane <me@mattfinucane.com>
ENV         NPM_CONFIG_LOGLEVEL warn
COPY        package.json /opt/package.json
WORKDIR     /opt
RUN         npm install -g webpack && npm install --loglevel verbose && npm cache verify

