language: node_js
node_js: "0.12.7"
before_install: 
- "curl https://install.meteor.com | /bin/sh"

before_script: 
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "export PATH=$HOME/.meteor:$PATH"
- "npm install -g velocity-cli"
- "sleep 10"
script:
- "sh test-app.sh"
