version: '3'

services:
    mf-site-build:
      container_name: mf_site_build
      build:
        context: .docker/site
        dockerfile: Dockerfile
        args:
          hugo_version: "0.23"
      volumes:
        - ./:/opt:rw
      command: hugo -s /opt/site -b http://mattfinucane.build --config=./site/build.yml -d ../public

    mf-nginx-build:
      container_name: mf_nginx_build
      build:
        context: .docker/nginx
        dockerfile: Dockerfile
        args:
          nginx_conf: nginx.build.conf
      volumes:
        - ./media:/opt/media:ro
        - ./public:/opt/public:ro
      links: 
        - mf-site-build
      ports:
        - "80:80"
      command: nginx -g "daemon off;"

    mf-gulp-build:
      image: node:8.0.0-alpine
      container_name: mf_dependencies_build
      environment:
        - SCRIPTS_DEST=./public/js/
        - SVG_DEST=./public/svg/
        - FAVICONS_DEST=./public/favicons/
      volumes:
        - ./:/opt:rw
      links: 
        - mf-site-build
      depends_on:
        - mf-site-build
      command: sh -c "npm install -g gulp && npm link gulp && cd /opt && npm install && npm start"

    mf-sass-dev:
      container_name: mf_sass_build
      image: ruby:2.1-alpine
      volumes:
        - ./:/opt:rw
      links:
        - mf-site-build
      depends_on:
        - mf-site-build
      command: sh -c "gem install sass && sass /opt/assets/sass/main.sass:/opt/public/css/main.css --style compressed --sourcemap=none"