version: '3'

services:
  mf-site-dev:
    container_name: mf_site_dev
    restart: on-failure
    build:
      context: .docker/site
      dockerfile: Dockerfile
      args:
        hugo_version: "0.23"
    ports: 
      - "1313:1313"
    volumes: 
      - .:/opt:rw
    command: hugo server -s /opt/site --config /opt/site/config.yml --baseURL http://mattfinucane.local/ --bind "0.0.0.0" --appendPort=false --verbose

  mf-nginx-dev:
    container_name: mf_nginx_dev
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.development.conf
    volumes:
      - ./media:/opt/media:ro
    links: 
      - mf-site-dev
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
    
  mf-webpack-dev:
    container_name: mf_webpack_dev
    restart: on-failure
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile.development
    volumes:
      - .:/opt:rw
      - /opt/node_modules
    command: ["npm", "run", "start:dev"]

