version: '3'

services:
  mf-site-dev:
    container_name: site_dev
    restart: always
    build:
      context: .docker/site
      dockerfile: Dockerfile
      args:
        hugo_version: "0.20.2"
    ports: 
      - "1313:1313"
    volumes: 
      - ./:/opt:rw
    command: hugo server -s /opt/mattfinucane --config /opt/mattfinucane/config.yml --baseURL http://mattfinucane.dev/ --bind "0.0.0.0" --appendPort=false --verbose

  mf-nginx-dev:
    container_name: nginx_dev
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.development.conf
    volumes:
      - ./media:/opt/media:ro
    links: 
      - mf-site-dev
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

  mf-dependencies-dev:
    image: node:7.9.0
    container_name: dependencies_dev  
    volumes:
      - ./:/opt:rw
    links:
      - mf-site-dev
    depends_on:
      - mf-site-dev
    command: sh -c "cd /opt && npm install -g gulp && npm install"

  mf-gulp-dev:
    image: node:7.9.0
    container_name: gulp_dev
    restart: always
    environment: 
      - SCRIPTS_DEST=./mattfinucane/static/js/
      - STYLES_DEST=./mattfinucane/static/css/
      - SVG_DEST=./mattfinucane/static/svg/
      - FAVICONS_DEST=./mattfinucane/static/favicons/
    volumes:
      - ./:/opt:rw
    links:
      - mf-site-dev
      - mf-dependencies-dev
    depends_on:
      - mf-dependencies-dev
      - mf-site-dev
    command: sh -c "cd /opt && npm link gulp && gulp"