---
baseURL:                "http://mattfinucane.build"
languageCode:           "en-ie"
title:                  "Matt Finucane"
disableLiveReload:      true
watch:                  false
preservetaxonomynames:  true

params:
  description:   "Freelance software engineer based in Berlin, Germany"
  author:        "Matt Finucane"
  title_first:   "Matt"
  title_last:    "Finucane"
  cl_video_base: "https://res.cloudinary.com/matt-finucane-portfolio/video/upload/ac_none"
  no_index:      true

menu:
  main:
    - name:        "home"
      identifier:  "home"
      url:         "/"
      weight:      1
    - name:        "projects"
      identifier:  "projects"
      url:         "/projects"
      weight:      2
    - name:        "cv"
      identifier:  "cv"
      url:         "/cv"
      weight:      3
    - name:        "about"
      identifier:  "about"
      url:         "/about"
      weight:      4
    - name:        "Blog"
      identifier:  "blog"
      url:         "/blog"
      weight:      5
    - name:        "hire me"
      identifier:  "hire-me"
      url:         "/hire-me"
      weight:      6

taxonomies:
  language:       "Languages"
  framework:      "Frameworks"
  infrastructure: "Infrastructure"
  tool:           "Tools"
...